DECLARE @SITUACAO CHAR(1)

SET @SITUACAO ='I'

IF (@SITUACAO = 'A')
BEGIN
	SELECT * FROM Tabela WHERE (Situacao = 'A') ORDER BY Nome ASC
END
ELSE IF (@SITUACAO = 'I')
BEGIN
	SELECT * FROM Tabela WHERE (Situacao = 'I') ORDER BY Nome ASC
END
ELSE IF (@SITUACAO <> 'A') AND (@SITUACAO <> 'I')
BEGIN
	PRINT 'INFORME O CÓDIGO ADEQUADO'
END
